version: '2'

services:
    ci:
        image: docteurklein/compose-ci
        build: .
        environment:
            GITHUB_TOKEN: $GITHUB_TOKEN
            LOG_LEVEL: DEBUG
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    tests:
        build: .
        command: bin/run-tests
        environment:
            GITHUB_TOKEN: $GITHUB_TOKEN
            commit: $commit
        volumes:
            - .:/ci
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - ci
